const cats=['Früchte & Gemüse','Fleisch & Fisch','Kühlregal','Brot','Vorrat','Tiefkühl','Snacks','Haushalt','Sonstiges'];
const SUPABASE_URL='https://uoqastprrdlwlsesheoz.supabase.co';
const SUPABASE_KEY='sb_publishable_vCRrqr_Zi1Zg1jN-LOrV3Q_7I0LnzKu';
const STATE_URL=SUPABASE_URL+'/rest/v1/household_state?id=eq.familie';
const API_HEADERS={'apikey':SUPABASE_KEY,'Authorization':'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'};
const initialStaples=[
['5 × Coop Knusper-Joghurt Schokolade','Kühlregal'],['2 × Milch 0.5 l','Kühlregal'],['Butter','Kühlregal'],['Caprice des Dieux','Kühlregal'],['Gouda Scheiben','Kühlregal'],['Eier, 10er','Kühlregal'],['Ganzes Brot','Brot'],['Gipfeli, falls Frühstück zu Hause','Brot'],['Toastbrot, Vorrat prüfen','Brot'],['Konfitüre, Vorrat prüfen','Vorrat'],['Salami','Kühlregal'],['Truten-/Pouletbrust, Schweizer Fleisch','Kühlregal'],['Bündnerfleisch','Kühlregal'],['1 × Migros Grapefruitsaft 0.75 l','Vorrat'],['Pasta, Vorrat prüfen','Vorrat'],['Barilla Pesto Genovese, Vorrat prüfen','Vorrat'],['Tomatensauce, Vorrat prüfen','Vorrat'],['Sojasauce, Vorrat prüfen','Vorrat'],['Mayonnaise, Vorrat prüfen','Vorrat'],['Senf, Vorrat prüfen','Vorrat'],['Hot Sauce, Vorrat prüfen','Vorrat'],['Currypulver, Vorrat prüfen','Vorrat'],['Knorr Suppe, Vorrat prüfen','Vorrat'],['Knorr Kartoffelstock/Fertiggericht, Vorrat prüfen','Vorrat'],['TK Lachs, Vorrat prüfen','Tiefkühl'],['TK Spinat, Vorrat prüfen','Tiefkühl'],['Ofen-Pommes, Vorrat prüfen','Tiefkühl'],['TK Gemüsemischung, Vorrat prüfen','Tiefkühl'],['Findus Käse-/Pilzplätzli, Vorrat prüfen','Tiefkühl'],['TK Aprikosen/Zwetschgen, Vorrat prüfen','Tiefkühl'],['Zweifel Chips, bei Bedarf','Snacks'],['Schokolade, bei Bedarf','Snacks'],['WC-Papier, nur Grosspackung/Aktion','Haushalt'],['Haushaltpapier Short & Smart, nur Grosspackung/Aktion','Haushalt']];
const initialMeals={
'Spaghetti Tomatensauce':['Spaghetti','Tomatensauce','Gruyère Reibkäse'],'Spaghetti Pesto':['Spaghetti','Barilla Pesto Genovese','Gruyère Reibkäse'],'Fajitas mit Poulet':['Poulet','Fajita-Wraps','Salat','Salsa','Cheddar Reibkäse','Crème fraîche','Jalapeños'],'Rösti + Spiegelei':['Fertigrösti','Eier'],'Oopsie Smash Burger':['Rindshackfleisch [frisch]','Cheddar Scheiblettenkäse','Salat','Zwiebeln','Burger Bacon Sauce','Philadelphia Light','Eier'],'Wienerli + Brot + Suppe':['Wienerli','Brot','Knorr Suppe'],'Curryhack + Kartoffeln':['Rindshackfleisch [frisch]','Kartoffeln','Currypulver','Halbrahm'],'Lachs + Kartoffeln + Spinat':['TK Lachs','Kartoffeln','TK Spinat'],'Aufschnitt + Brot':['Brot','Aufschnitt'],'Poulet + Reis':['Poulet','Reis','Sojasauce'],'Pizza':['Pizzateig','Pizzasauce','Mozzarella','Champignons','Schinken','Zwiebeln'],'Käseplätzli + Spinat':['Findus Käseplätzli','TK Spinat'],'Pouletschnitzel + Pommes':['Paniertes Pouletschnitzel','Ofen-Pommes'],'Grillieren':['Pouletspiess oder OLMA-Bratwurst','Brot oder Gnocchi','Salat']};
const freshState=()=>({staples:initialStaples.map((x,i)=>({id:'s'+i,name:x[0],cat:x[1],active:true})),meals:initialMeals,checked:{},extra:[],menu:{So:'',Mo:'',Di:'',Mi:'',Do:'',Fr:''}});
let state=JSON.parse(localStorage.getItem('einkaufState')||'null')||freshState();
let cloudReady=false,saveTimer=null,lastCloud='';
function localSave(){localStorage.setItem('einkaufState',JSON.stringify(state));}
async function cloudSave(){if(!cloudReady)return;const data=JSON.stringify(state);if(data===lastCloud)return;try{const r=await fetch(STATE_URL,{method:'PATCH',headers:{...API_HEADERS,'Prefer':'return=minimal'},body:JSON.stringify({data:state,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await r.text());lastCloud=data;}catch(e){console.error('Supabase speichern fehlgeschlagen',e)}}
function save(){localSave();clearTimeout(saveTimer);saveTimer=setTimeout(cloudSave,180);}
async function loadCloud(){try{const r=await fetch(STATE_URL+'&select=data',{headers:API_HEADERS,cache:'no-store'});if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(rows[0]&&rows[0].data&&Object.keys(rows[0].data).length){state=rows[0].data;}else{localSave();const p=await fetch(STATE_URL,{method:'PATCH',headers:{...API_HEADERS,'Prefer':'return=minimal'},body:JSON.stringify({data:state,updated_at:new Date().toISOString()})});if(!p.ok)throw new Error(await p.text());}lastCloud=JSON.stringify(state);cloudReady=true;localSave();syncMenuIngredients(false);renderAll();}catch(e){console.error('Supabase laden fehlgeschlagen',e);renderAll();}}
async function pollCloud(){if(!cloudReady)return;try{const r=await fetch(STATE_URL+'&select=data,updated_at',{headers:API_HEADERS,cache:'no-store'});if(!r.ok)return;const rows=await r.json();if(!rows[0]||!rows[0].data)return;const incoming=JSON.stringify(rows[0].data);if(incoming!==lastCloud){state=rows[0].data;lastCloud=incoming;localSave();renderAll();}}catch(e){console.error(e)}}
function catFor(n){let s=n.toLowerCase();if(/hack|poulet|wienerli|schinken|bratwurst|fleisch/.test(s))return'Fleisch & Fisch';if(/salat|zwiebel|kartoffel|champignon|jalape|trauben|kiwi|pfirsich|heidel|gurke|tomate/.test(s))return'Früchte & Gemüse';if(/käse|mozzarella|cheddar|rahm|philadelphia|ei|milch|joghurt|butter/.test(s))return'Kühlregal';if(/brot|gipfeli|toast/.test(s))return'Brot';if(/tk |pommes|findus/.test(s))return'Tiefkühl';return'Vorrat'}
function renderList(){let all=state.staples.filter(x=>x.active).map(x=>({...x,source:'Grundbedarf'})).concat(state.extra);let root=document.querySelector('#shoppingList');root.innerHTML='';cats.forEach(c=>{let a=all.filter(x=>x.cat===c).sort((a,b)=>(state.checked[a.id]?1:0)-(state.checked[b.id]?1:0));if(!a.length)return;let d=document.createElement('div');d.className='category';d.innerHTML=`<h3>${c}</h3>`;a.forEach(x=>{let r=document.createElement('div');r.className='item '+(state.checked[x.id]?'checked':'');r.innerHTML=`<input type="checkbox" ${state.checked[x.id]?'checked':''}><span class="label">${x.name}</span>${x.name.includes('[frisch]')?'<span class="tag">unter Woche frisch</span>':''}${x.source==='extra'?'<button class="delete">×</button>':''}`;r.querySelector('input').onchange=e=>{state.checked[x.id]=e.target.checked;save();renderList()};let del=r.querySelector('.delete');if(del)del.onclick=()=>{state.extra=state.extra.filter(y=>y.id!==x.id);save();renderList()};d.appendChild(r)});root.appendChild(d)})}
function syncMenuIngredients(doSave=true){state.extra=state.extra.filter(x=>x.source!=='menu');const seen=new Set();Object.values(state.menu).forEach(mealName=>{(state.meals[mealName]||[]).forEach(name=>{const key=name.trim().toLowerCase();if(!key||seen.has(key))return;seen.add(key);state.extra.push({id:'m_'+key.replace(/[^a-z0-9äöü]+/gi,'_'),name:name.trim(),cat:catFor(name),source:'menu'});});});if(doSave)save();}
function renderMenu(){let root=document.querySelector('#weekMenu');root.innerHTML='';let names=['','Auswärts / nichts','Knorr / einfach',...Object.keys(state.meals)];Object.keys(state.menu).forEach(day=>{let d=document.createElement('div');d.className='day';d.innerHTML=`<strong>${day}</strong><select>${names.map(n=>`<option ${state.menu[day]===n?'selected':''}>${n}</option>`).join('')}</select>`;d.querySelector('select').onchange=e=>{state.menu[day]=e.target.value;syncMenuIngredients();renderList()};root.appendChild(d)})}
function renderManage(){let s=document.querySelector('#staples');s.innerHTML='';state.staples.forEach(x=>{let r=document.createElement('div');r.className='mealrow';r.innerHTML=`<input type="checkbox" ${x.active?'checked':''}><span>${x.name}</span><button class="delete">×</button>`;r.querySelector('input').onchange=e=>{x.active=e.target.checked;save();renderList()};r.querySelector('.delete').onclick=()=>{state.staples=state.staples.filter(y=>y.id!==x.id);save();renderManage();renderList()};s.appendChild(r)});let m=document.querySelector('#meals');m.innerHTML='';Object.entries(state.meals).forEach(([n,ing])=>{let r=document.createElement('div');r.className='card';r.innerHTML=`<div class="mealrow"><strong>${n}</strong><button class="delete">×</button></div><div class="hint">${ing.join(' · ')}</div>`;r.querySelector('.delete').onclick=()=>{delete state.meals[n];Object.keys(state.menu).forEach(d=>{if(state.menu[d]===n)state.menu[d]=''});syncMenuIngredients();renderManage();renderMenu();renderList()};m.appendChild(r)})}
function renderAll(){renderList();renderMenu();renderManage();}
function addExtra(name,cat){if(!name.trim())return;state.extra.push({id:'e'+Date.now()+Math.random(),name:name.trim(),cat:cat||catFor(name),source:'extra'});save();renderList()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')});
document.querySelector('#quickAddBtn').onclick=()=>{addExtra(quickAdd.value);quickAdd.value=''};quickAdd.onkeydown=e=>{if(e.key==='Enter')quickAddBtn.click()};
document.querySelector('#resetWeek').onclick=()=>{if(confirm('Häkchen und Wochenmenü zurücksetzen?')){state.checked={};state.extra=[];state.menu={So:'',Mo:'',Di:'',Mi:'',Do:'',Fr:''};save();renderList();renderMenu()}};
cats.forEach(c=>newStapleCat.add(new Option(c,c)));addStaple.onclick=()=>{if(newStaple.value.trim()){state.staples.push({id:'s'+Date.now(),name:newStaple.value.trim(),cat:newStapleCat.value,active:true});newStaple.value='';save();renderManage();renderList()}};
addMeal.onclick=()=>{let n=mealName.value.trim(),ing=mealIngredients.value.split('\n').map(x=>x.trim()).filter(Boolean);if(n&&ing.length){state.meals[n]=ing;mealName.value='';mealIngredients.value='';save();renderManage();renderMenu()}};
renderAll();loadCloud();setInterval(pollCloud,2500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)pollCloud()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
