// Zusätzliche übermittelte Rezepte. Wird beim Laden und nach Cloud-Sync eingemischt,
// ohne bestehende oder selbst bearbeitete Rezepte zu überschreiben.
const suppliedRecipes={
  'Spargel-Kartoffelsalat mit wachsweichen Eiern':normalizeRecipe({title:'Spargel-Kartoffelsalat mit wachsweichen Eiern',servings:2,source:'chat-photo',ingredients:['1 EL Senf','1 EL heller Essig, z.B. Apfelessig','0.5 EL flüssiger Honig','0.125 Bund Schnittlauch, geschnitten','Salz','Pfeffer','150 g Frühkartoffeln','200 g grüne Spargeln','2–4 Eier','0.5 Bund Radiesli'],instructions:['Senf bis und mit Schnittlauch verrühren, Sauce würzen.','Kartoffeln in Salzwasser knapp weich garen. Spargeln die letzten ca. 3 Minuten mitkochen. Abgiessen und auskühlen lassen.','Eier 7 Minuten kochen, kalt abschrecken, schälen und halbieren.','Kartoffeln und Spargeln mit der Salatsauce mischen, auf Tellern anrichten. Eier und Radiesli darauf verteilen.']}),
  'Helle und dunkle Toblerone-Mousse':normalizeRecipe({title:'Helle und dunkle Toblerone-Mousse',servings:2,source:'chat-photo',ingredients:['50 g weisse Toblerone','0.5 Stk. frisches Ei, klein','0.5 dl Vollrahm','50 g dunkle Toblerone, zartbitter','0.5 EL Puderzucker','0.5 Stk. frisches Ei, klein','0.5 dl Vollrahm','1 TL gehackte Pistazien, zum Verzieren'],instructions:['Helle Mousse: Weisse Toblerone zerbröckeln, in eine Schüssel geben, im Wasserbad schmelzen und glatt rühren. Ei darunterrühren. Rahm steif schlagen und sorgfältig darunterziehen. Zugedeckt ca. 3 Stunden kühl stellen.','Dunkle Mousse: Dunkle Toblerone zerbröckeln, in eine Schüssel geben, im Wasserbad schmelzen und glatt rühren. Ei und Puderzucker verrühren und unter die Schokolade rühren. Rahm steif schlagen und sorgfältig darunterziehen. Zugedeckt ca. 3 Stunden kühl stellen.','Servieren: Die beiden Mousses mit zwei heiss abgespülten Esslöffeln abstechen, auf Tellern anrichten und mit Pistazien verzieren.']}),
  'Bratapfel-Crumble auf Zimtcreme':normalizeRecipe({title:'Bratapfel-Crumble auf Zimtcreme',servings:2,source:'chat-photo',ingredients:['32 g weiche Butter','50 g Mehl','16 g Zucker','0.4 Packung Bourbon-Vanillezucker','Zimt','1.2 Stk. Äpfel','0.4 Stk. Zitrone, Saft','0.4 Stk. Zimtstange','0.4 Stk. Sternanis','40 ml Orangensaft','0.4 Tropfen Bittermandelöl','0.8–1.2 EL brauner Zucker','100 g Quark (20 %)','80 ml Sahne','20 g Puderzucker','0.4 TL Zimt','0.4 TL Vanille-Extrakt'],instructions:['Backofen auf 175 °C (150 °C Umluft) vorheizen.','Für die Streusel Butter, Zucker, Vanillezucker und Mehl mit den Fingern zu kleinen Streuseln verreiben. Auf ein mit Backpapier belegtes Blech geben und ca. 15 Minuten golden ausbacken.','Für das Kompott Äpfel schälen, Kerngehäuse entfernen, achteln und in Stücke schneiden. In einer Auflaufform sofort mit Zitronensaft mischen. Zimtstange und Sternanis darunter verstecken, Orangensaft angiessen und Zucker darüber verteilen.','Äpfel im vorgeheizten Ofen 20–25 Minuten braten und gelegentlich umrühren. Das Kompott soll weich werden, aber noch etwas Biss haben. Abkühlen lassen und bis zur Verwendung kalt stellen.','Für die Zimtcreme Sahne steif schlagen und Quark einrühren. Mit Zimt, Puderzucker und Vanille würzen, glatt rühren und bis zum Gebrauch kalt stellen.','Zum Servieren zuerst die Creme in Gläser geben, dann die Bratapfelmasse darauf verteilen und zuletzt die Streusel darüberkrümeln. Nach Wunsch mit angerösteten Mandelplättchen garnieren.']}),
  'Hüttenkäse-Wraps':normalizeRecipe({title:'Hüttenkäse-Wraps',servings:2,source:'chat-web',ingredients:['400 g Hüttenkäse nature','2 Stk. frische Eier','40 g geriebener Gruyère','0.25 TL Salz','Pfeffer','100 g Crème fraîche','2 Stk. Tomaten','2 Stk. Snackgurken','Jalapeños','Schinken'],instructions:['Ofen auf 170 °C Heissluft vorheizen. Hüttenkäse mit Eiern und Gruyère pürieren und mit Salz und Pfeffer würzen. Die Masse auf mit Backpapier belegte Bleche verteilen und zu Rechtecken ausstreichen.','Ca. 35 Minuten backen. Herausnehmen und die Hüttenkäsefladen auf dem Blech auskühlen lassen. Mit dem Backpapier wenden, Papier sorgfältig abziehen und die Fladen quer halbieren.','Fladen mit Crème fraîche bestreichen. Tomaten und Snackgurken in Scheiben schneiden und zusammen mit Jalapeños und Schinken darauf verteilen. Zu Wraps aufrollen.']})
};
function mergeSuppliedRecipes(){state.recipes=state.recipes||{};Object.entries(suppliedRecipes).forEach(([name,recipe])=>{if(!state.recipes[name])state.recipes[name]=recipe;});}
const baseMigrate=migrate;migrate=function(){baseMigrate();mergeSuppliedRecipes();};mergeSuppliedRecipes();localSave();
